/* Generated By:JJTree&JavaCC: Do not edit this line. HowdyLangParserConstants.java */
package org.example;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface HowdyLangParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int HOLLER = 5;
  /** RegularExpression Id. */
  int IF_YALL = 6;
  /** RegularExpression Id. */
  int ELSE_YALL = 7;
  /** RegularExpression Id. */
  int WHILE_YALL = 8;
  /** RegularExpression Id. */
  int DO_YALL = 9;
  /** RegularExpression Id. */
  int TIMES = 10;
  /** RegularExpression Id. */
  int ASSIGN = 11;
  /** RegularExpression Id. */
  int EQ = 12;
  /** RegularExpression Id. */
  int SEMI = 13;
  /** RegularExpression Id. */
  int LPAR = 14;
  /** RegularExpression Id. */
  int RPAR = 15;
  /** RegularExpression Id. */
  int LBRA = 16;
  /** RegularExpression Id. */
  int RBRA = 17;
  /** RegularExpression Id. */
  int BEGIN = 18;
  /** RegularExpression Id. */
  int END = 19;
  /** RegularExpression Id. */
  int STRING_LITERAL = 20;
  /** RegularExpression Id. */
  int IDENTIFIER = 21;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"HOLLER\"",
    "\"IF_YALL\"",
    "\"ELSE_YALL\"",
    "\"WHILE_YALL\"",
    "\"DO_YALL\"",
    "\"TIMES\"",
    "<ASSIGN>",
    "<EQ>",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"MAKE_PROGRAMMING\"",
    "\"GREAT_AGAIN\"",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
  };

}
